language: python

python:
  - "3.7.5"
  - "3.8.2"

env:
  - TEST_SUITE=testOnlyDocTests
  - TEST_SUITE=test

cache:
  directories:
    - $HOME/stanza_resources/
    - $HOME/cltk_data/
    - $HOME/virtualenv/
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - graphviz

before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - make install
  - poetry run python scripts/download_misc_dependencies.py

before_script:
  - poetry run pre-commit install-hooks
#  - poetry run pre-commit run --all-files

script:
  - make $TEST_SUITE
  - make uml
  - make docs

after_failure:
  - echo Add later
